FROM php:8.3-fpm-bookworm

# system deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    git unzip libpq-dev libzip-dev ca-certificates \
 && docker-php-ext-install pdo_pgsql zip opcache \
 && rm -rf /var/lib/apt/lists/*

# composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
